//! Command-based API for Centrifugo capability
//!
//! This module provides the new Command API for Centrifugo operations,
//! replacing the deprecated Capability API.
//!
//! It reuses the Operation and Output types from the deprecated capability
//! to ensure compatibility with the Effect enum generated by the macro.

use std::marker::PhantomData;

use crux_core::{command, Command};

// Re-export types from the deprecated capability module
// This ensures the Effect enum generated from Capabilities struct
// has the correct From<Request<CentrifugoOperation>> implementation
pub use super::centrifugo::{CentrifugoOperation, CentrifugoOutput};

/// Command-based Centrifugo API
pub struct Centrifugo<Effect, Event> {
    effect: PhantomData<Effect>,
    event: PhantomData<Event>,
}

impl<Effect, Event> Centrifugo<Effect, Event>
where
    Effect: Send + From<crux_core::Request<CentrifugoOperation>> + 'static,
    Event: Send + 'static,
{
    /// Connect to Centrifugo server
    pub fn connect() -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::Connect)
    }

    /// Disconnect from Centrifugo server
    pub fn disconnect() -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::Disconnect)
    }

    /// Subscribe to a specific channel
    pub fn subscribe(channel: impl Into<String>) -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::Subscribe {
            channel: channel.into(),
        })
    }

    /// Unsubscribe from a specific channel
    pub fn unsubscribe(channel: impl Into<String>) -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::Unsubscribe {
            channel: channel.into(),
        })
    }

    /// Subscribe to all known channels
    pub fn subscribe_all() -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::SubscribeAll)
    }

    /// Unsubscribe from all channels
    pub fn unsubscribe_all() -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::UnsubscribeAll)
    }

    /// Get history (last message) from a channel
    pub fn history(channel: impl Into<String>) -> RequestBuilder<Effect, Event> {
        RequestBuilder::new(CentrifugoOperation::History {
            channel: channel.into(),
        })
    }
}

/// Request builder for Centrifugo operations
#[must_use]
pub struct RequestBuilder<Effect, Event> {
    operation: CentrifugoOperation,
    effect: PhantomData<Effect>,
    event: PhantomData<fn() -> Event>,
}

impl<Effect, Event> RequestBuilder<Effect, Event>
where
    Effect: Send + From<crux_core::Request<CentrifugoOperation>> + 'static,
    Event: Send + 'static,
{
    fn new(operation: CentrifugoOperation) -> Self {
        Self {
            operation,
            effect: PhantomData,
            event: PhantomData,
        }
    }

    /// Build the request into a Command RequestBuilder
    pub fn build(
        self,
    ) -> command::RequestBuilder<Effect, Event, impl std::future::Future<Output = CentrifugoOutput>>
    {
        command::RequestBuilder::new(move |ctx| async move {
            Command::request_from_shell(self.operation)
                .into_future(ctx)
                .await
        })
    }
}
