ARG DOCKER_NAMESPACE=omnectweucopsacr.azurecr.io
ARG VERSION_RUST_CONTAINER=1.89.0-bookworm
ARG DISTROLESS_IMAGE=gcr.io/distroless/base-debian12:nonroot

FROM ${DISTROLESS_IMAGE} AS distroless

# Stage 1: Generate TypeScript types on host architecture (fast, no emulation)
FROM --platform=$BUILDPLATFORM ${DOCKER_NAMESPACE}/rust:${VERSION_RUST_CONTAINER} AS typegen

# Install pnpm for TypeScript type generation
RUN curl -fsSL https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL=/bin/bash bash - && \
    ln -s "$HOME/.local/share/pnpm/pnpm" /usr/local/bin/pnpm

WORKDIR "/work"

COPY Cargo.lock Cargo.toml ./
COPY src ./src

# Build shared_types to generate TypeScript bindings (runs on host arch, fast)
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --release -p shared_types

# Stage 2: Build Crux WASM core (parallel with typegen)
FROM --platform=$BUILDPLATFORM ${DOCKER_NAMESPACE}/rust:${VERSION_RUST_CONTAINER} AS wasm-build

# Install wasm-pack
RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

WORKDIR /work

COPY Cargo.lock Cargo.toml ./
COPY src ./src

# Build WASM module for Crux core
RUN cd src/app && wasm-pack build --target web --out-dir ../ui/src/core/pkg

# Stage 3: Install Vue dependencies (parallel with typegen and wasm-build)
FROM oven/bun AS vue-install
RUN mkdir -p /tmp
COPY src/ui/package.json /tmp
COPY src/ui/bun.lock /tmp
RUN cd /tmp && bun install --frozen-lockfile

# Stage 4: Build Vue UI using generated types and WASM from previous stages
FROM oven/bun AS vue-build
WORKDIR /usr/src/app
COPY src/ui .
# Use TypeScript types generated by the typegen stage (built on host arch)
COPY --from=typegen /work/src/shared_types/generated/typescript ../shared_types/generated/typescript
# Copy WASM package from wasm-build stage
COPY --from=wasm-build /work/src/ui/src/core/pkg ./src/core/pkg
COPY --from=vue-install /tmp/node_modules node_modules
# Remove CommonJS .js files so Vite uses the TypeScript source directly
RUN find ../shared_types/generated/typescript -name "*.js" -delete
RUN bun run build

# Stage 5: Build Rust backend for target architecture with embedded frontend
FROM ${DOCKER_NAMESPACE}/rust:${VERSION_RUST_CONTAINER} AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    cmake \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ARG TARGETARCH
ARG OMNECT_UI_BUILD_ARG=""
WORKDIR "/work"

ARG CENTRIFUGO_VERSION=v6.1.0

RUN curl -sSLf https://centrifugal.dev/install.sh | sh

COPY --from=distroless /var/lib/dpkg/status.d /distroless_pkgs

COPY Cargo.lock Cargo.toml ./
COPY src ./src

# Copy built Vue frontend for embedding into the Rust binary
COPY --from=vue-build /usr/src/app/dist ./src/ui/dist

# Build omnect-ui for target architecture with embedded frontend
# Cache mounts persist compiled dependencies across builds
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/work/build \
    cargo build ${OMNECT_UI_BUILD_ARG} --release -p omnect-ui --target-dir ./build

COPY .git ./.git
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/work/build <<EOF
  set -e
  # update timestamps to force a new build with git info
  touch /work/src/backend/src/main.rs
  cargo build ${OMNECT_UI_BUILD_ARG} --release -p omnect-ui --target-dir ./build
  # Copy binary out of cache mount so it's available in subsequent layers
  cp ./build/release/omnect-ui /work/omnect-ui-bin
EOF

SHELL ["/bin/bash", "-c"]
RUN <<EOT
    set -eu

    mkdir -p /copy/status.d

    executable=(omnect-ui-bin)

    mkdir -p /copy/$(dirname "${executable}")
    cp "${executable}" /copy/"${executable}"

    # gather libraries installed in distroless image to skip them
    readarray -t FILTER < <(for file in $(find /distroless_pkgs -type f -! -name "*.md5sums"); do sed -n "s/Package: \(.*\)$/\1/p" $file; done)

    # skip .so of the dynamic linker
    LOADER=$(readelf -l "${executable}" | grep "interpreter:" | sed -e "s/.*interpreter: \(.*\)]$/\1/")

    readarray -t LIBS < <(ldd "${executable}" | awk '{if ($3 == "") print $1; else print $3}')

    for LIB in ${LIBS[@]}; do
        # skip the linker loader
        if [ "$LIB" == "$LOADER" ]; then
            continue
        fi

        # the actual library location in the package may deviate from what the
        # linker specifies, so update that info and gather the package name.
        PKG_INFO=$(LOCALE=C.UTF-8 dpkg -S "*$LIB" 2> /dev/null) || continue
        PKG="${PKG_INFO%%:*}"
        LIB="${PKG_INFO##*: }"

        # skip libraries already installed in distroless
        if [[ " ${FILTER[*]} " =~ "${PKG} " ]]; then
            continue
        fi

        # copy the library and its dpkg database entries
        mkdir -p /copy/$(dirname "${LIB}")
        cp "${LIB}" /copy/"${LIB}"
        sed -n "/Package: ${PKG}/,/^$/p" /var/lib/dpkg/status > "/copy/status.d/${PKG}"
    done
EOT

RUN mkdir /cert

# Final stage: Assemble the runtime image
FROM ${DISTROLESS_IMAGE} AS base
COPY --from=builder --chown=10000:10000 /cert /cert
COPY --from=builder /work/omnect-ui-bin /omnect-ui
COPY --from=builder /work/centrifugo /
COPY --from=builder /copy/lib/ /lib/
COPY --from=builder /copy/status.d /var/lib/dpkg/status.d

WORKDIR "/"
COPY src/backend/config/centrifugo_config.json /

ENTRYPOINT [ "/omnect-ui" ]
